BaSP-m2023/juvi-megarocket-app

src/Components/Admins/Form/form.module.css
src/Components/Admins/Form/index.jsx
src/Components/Admins/Table/index.jsx
src/Components/Admins/Table/table.module.css
src/Components/Admins/admins.module.css
src/Components/Admins/index.js

Added Form component.
Added Table component.
Added functionalities.
Added styles for components and main screen.

BaSP-MR-53: Admins Screen

---

src/Components/Members/AddForm/index.jsx
src/Components/Members/UpdateForm/index.jsx
src/Components/Members/index.js

Two new buttons to cancel additions in "Add members" and "Edit member".. When completing any of the two successfully, the form closes automatically

BaSP-MR-65: bugs from create and update fixed

---

src/Components/SuperAdmins/Form/Index.jsx
src/Components/SuperAdmins/index.js

fix the bug of the doble alert!

BaSP-MR-82: Fix the bug

---

src/Components/Shared/ModalAlert/index.jsx

Implemented fixes so the modal works correctly

BasP-MR-94:Modal Confirm Fixes implemented

---

src/Components/Shared/Table/index.jsx

Added the new ModalConfirm
Added logic to use both buttons to make it work

BasP-MR-96:Added ModalConfirm, added logic to use it

---

src/Components/Shared/Input/index.jsx
src/Components/Shared/Input/index.jsx.jsx
src/Components/Shared/Input/input.module.css

Created input component.
Added to style to input.

BasP-MR-75: Shared Input

---

src/Components/Shared/Table/index.jsx

Ticket: https://trello.com/c/39NSIzaW/98-fix-share-table
FIX => Always deletes the last row of the table

BasP-MR-98: Fix table

---

src/Components/Classes/Form/index.jsx

Added logic to set IsTrue ="true" after a success creation of a new class

BaSP-MR-99:Classes create fix

---

src/Components/Admins/Form/index.jsx
src/Components/Admins/index.js
src/Components/Layout/index.js

fixed error for admin screen . added "exact path" in layout general

BaSP-MR-100: fix screens for admin

---

src/Components/Activities/index.js
src/Components/Admins/Form/index.jsx
src/Components/Layout/index.js

[FIX] SP-MR-104: layout imports, activity modal button, admin create msg

---

src/Components/Admins/Form/index.jsx
src/Components/Admins/index.js
src/Components/Shared/Table/index.jsx

In this PR the Tickets MR-100 and MR-88 got fixed
I had to add new logic to check if the value that will be displayed is a password to replace that with "********"
I remove repeated logic that was displaying a confirmation for the delete twice
I changed the logic so if we got a success message from the create or the edit we flag a bool value so when we close the confirmation modal it takes you to the page you where before

BaSP-MR-100/admin fix screen

---

src/Components/Subscriptions/Form/index.jsx

Fixed logic so now the confirmation modal shows 
Fixed logic so now the date and time shows when you are editing a subscription
Removed one console.log
Sadly it seems the second error its kind of random so I don't know how to fix that 😢 
Trello ticket 
https://trello.com/c/dBdy2Zkd/106-bug-editing-and-creating-a-subscription

BaSP-MR-106:fixed changes requested on ticket

---

src/Components/Admins/index.js

Added logic to change state of a Boolean to show the modal after a success delete

BaSP-MR-100:Alert is now show

---

package-lock.json
package.json
src/Components/Admins/Form/index.jsx
src/index.js
src/redux/admins/actions.js
src/redux/admins/constants.js
src/redux/admins/reducer.js
src/redux/admins/thunks.js
src/redux/store.js

BaSP-MR-109: Redux set up

---

package-lock.json
package.json
src/Components/Admins/Form/index.jsx
src/index.js
src/redux/admins/reducer.js
src/redux/store.js

Trello: https://trello.com/c/pPyt0znp/119-fix-redux-set-up
The initial redux configuration was fixed by removing libraries and installing new ones. We also removed unnecessary logic.

BasP-MR-119: Fix setup Redux

---

src/Components/Members/MemberForm/form.module.css
src/Components/Members/members.module.css

**Changes:**
- Now it has more responsive design
- It displays fine whatever zoom you apply to the browser

BaSP-MR-117:  Member form css changed

---

src/Components/Footer/footer.module.css
src/Components/Footer/index.js
src/Components/Header/header.module.css
src/Components/Header/index.js

Changed html structure in both footer and header
Edited css for both to maintain the page style

BaSP-MR-107:HTML Nesting fix

---

src/Components/Admin/Activities/Form/index.jsx
src/Components/Admin/Members/MemberForm/index.jsx
src/Components/Member/Activity/activity.module.css
src/Components/Member/Activity/index.js
src/Routes/activity/form.jsx
src/Routes/activity/index.jsx
src/Routes/admin/form.jsx
src/Routes/admin/index.jsx
src/Routes/class/form.jsx
src/Routes/class/index.jsx
src/Routes/index.jsx
src/Routes/member/form.jsx
src/Routes/member/index.jsx
src/Routes/subscription/form.jsx
src/Routes/subscription/index.jsx
src/Routes/super-admin/form.jsx
src/Routes/super-admin/index.jsx
src/Routes/trainer/form.jsx
src/Routes/trainer/index.jsx

The layout of member activities has been added, and the routes folder has been modified so that all routes are exported absolutely and the code is simpler and more readable.

BaSP-MR-143: Simplify routes and added styles for activity member layout

---

src/Components/Admin/Admins/Form/index.jsx
src/Components/Admin/Admins/index.js
src/Components/Member/Activity/index.js

Now if you edit, add or delete an activity you can modify it from the members/activites tab and a general admin error has been corrected.
Edited the activities from the database to be the same as figma's.

 BaSP-MR-149: Card linked to database

---

src/Components/SuperAdmins/Form/Index.jsx
src/Components/SuperAdmins/Form/validation.js

In this pull request, we are using the useForm hook in the superAdmins form.

BaSP-MR-139: React hook form superAdimns.

---

src/Components/SuperAdmins/Form/validation.js

Both the regexes and the error messages were modified to comply with what was requested by the QA's

BaSP-MR-129: fix to alerts in superAdmin

---

src/Components/Member/Profile/index.jsx
src/Components/Member/Profile/memberProfileValidations.js
src/Routes/index.jsx

Added profile editting form.
Used lazy imports.
Form using react hook.
Added routes.
Note: No member should be edited on the table, this will be implemented next week.
Ticket link: https://trello.com/c/E1oboVju/142-member-profile

BaSP-MR-142: Member Profile Screen

---

src/Components/Admin/Members/MemberForm/index.jsx
src/Components/Admin/Members/MemberForm/memberFormValidations.js

**Changes:**
- `<MemberForm />`: `phone` and `dni` fields now displays more friendly messages
- `<MemberForm />`: "Birth Day" label changed, now it's "Birth Date"

BaSP-MR-147: Member form fix [FIX]

---

.eslintignore
.gitignore
jsconfig.json
package-lock.json
package.json
src/Components/Admin/Activities/Form/index.jsx
src/Components/Admin/Activities/index.js
src/Components/Admin/Classes/Form/index.jsx
src/Components/Admin/Classes/index.jsx
src/Components/Admin/Members/MemberForm/index.jsx
src/Components/Admin/Members/index.js
src/Components/Admin/Trainers/Form/index.jsx
src/Components/Admin/Trainers/index.jsx
src/Components/Header/index.js
src/Components/Member/Activity/index.js
src/Components/Member/Membership/index.js
src/Components/Member/Profile/index.jsx
src/Components/Member/SignUp/index.jsx
src/Components/Navbar/index.js
src/Components/Shared/Button/index.jsx
src/Components/Shared/Input/index.jsx
src/Components/Shared/ModalAlert/index.jsx
src/Components/Shared/ModalConfirm/index.jsx
src/Components/Shared/Table/index.jsx
wdio.conf.js

All test id setup and webdriverIO with allure reporter

BaSP-MR-163: testid and wdio setup

---

src/Components/Navbar/index.js
src/Components/Shared/ModalConfirm/index.jsx

Small fixes in navbar and confirm modal test ids.
There is an issue with the navbar styles, please take it into  account. 
Bug ticket is already reported, I left here the link: https://trello.com/c/c3sUSssI

BaSP-MR-165: fix in navbar and confirmModal testid

---

src/redux/auth/reducer.js

**Changes**
- added ``default`` case inside the ``switch`` in auth ``reducer``

[FIX] BaSP-MR-169: reducer fixed

---

src/Routes/privateRoute.jsx

Ticket: https://trello.com/c/daXMUFbx/160-add-protected-routes-in-the-front-end
Creation of PrivateRoute.
It is pending in new tickets the implementation and improvement of the routes that we had old to improve the order of the application. :muscle:

BaSP-MR-160:  Creation of PrivateRoute

---

src/Components/Member/SignUp/index.jsx

**New**
-Sign Up form created (Now new members can be created)

BaSP-MR-155: Sign Up

---

src/Components/Login/index.jsx
src/Components/Login/login.module.css
src/Components/Login/loginValidations.js
src/Components/Navbar/index.js
src/Routes/index.jsx
src/redux/auth/thunks.js

added login form
added styles for the form 
added logic to save the token and role in localstorage

BaSP-MR-157: Login

---

src/Components/Member/Profile/index.jsx
test/README.md
test/pageObjects/admin/activities/activitiesForm.js
test/pageObjects/admin/activities/activitiesTable.js
test/pageObjects/member/profile/profileForm.js
test/pageObjects/sharedComponents/modalConfirm.js
test/specs/admin-e2e.js
test/specs/member-e2e.js
wdio.conf.js

In this PR, automated tests are added for the admin entities, for the CRUD of an activity. And for a member, the editing of their profile.
It doesn't have to be approved or merged.

BaSP-MR-173: automation for admin-activities and member-profile

---

src/Components/Signs/SignUp/index.jsx
src/redux/activities/thunks.js
src/redux/admins/thunks.js
src/redux/classes/thunks.js
src/redux/members/thunks.js
src/redux/subscriptions/thunks.js
src/redux/superadmins/thunks.js
src/redux/trainers/thunks.js

Added missing parameter for the headers for all the puts and post

BaSP-MR-183: Fix sing up 

---

src/Components/Signs/SignIn/index.jsx
src/Routes/index.jsx
src/redux/auth/thunks.js
src/redux/members/thunks.js

**Changes**
- Modals now displays as intended
- Success modal now drive you to the corresponding role route
**Note**
*"When you sign-in with a Super Admin account the route don't exist due the role need to be change serverside"*
SUPERADMIN to SUPER-ADMIN

BaSP-MR-179: Modals display [FIX]

---

src/Components/Admin/Activities/Form/index.jsx
src/Components/Admin/Activities/index.js
src/Components/Admin/Classes/Form/index.jsx
src/Components/Admin/Classes/index.jsx
src/Components/Admin/Members/MemberForm/index.jsx
src/Components/Admin/Members/index.js
src/Components/Admin/Trainers/Form/index.jsx
src/Components/Admin/Trainers/index.jsx
src/Components/Member/Profile/index.jsx
src/Components/Navbar/index.js
src/Components/Shared/ModalAlert/index.jsx
src/Components/Signs/Logout/index.js
src/Components/Signs/SignIn/index.jsx
src/Components/Signs/SignUp/index.jsx
test/pageObjects/admin/activities/activitiesForm.js
test/pageObjects/admin/activities/activitiesTable.js
test/pageObjects/member/profile/profileForm.js
test/pageObjects/sharedComponents/button.js
test/pageObjects/sharedComponents/modalAlert.js
test/pageObjects/sharedComponents/modalConfirm.js

In this branch I added new test-id and made some fixes in old ones.

MR-186: fixes in test id

---

src/Components/Admin/Members/MemberForm/index.jsx

A routing problem was solved in this PR.

BaSP-MR-167: new routes and edit password.

---

test/pageObjects/sharedComponents/logIn.js
test/specs/superadmin-e2e.js
test/specs/trainer-e2e.js
wdio.conf.js

Creation of e2e files for super admin and trainers and completed the log in process for each one.
For test now super admins gives you a fail because the routes doesn't work correctly yet.

Automation test - Super admin / trainers - Log in

---

src/Components/SuperAdmins/Form/Index.jsx
src/Components/SuperAdmins/index.jsx
test/pageObjects/superAdmin/adminCRUD.js
test/specs/superadmin-e2e.js

Added test id for the super admins page, and created the automation test for the crud of admins. (when merged will be corrected if is  necessary)

Automation MR:201/202 - Test id for super admin and test for admins crud

---

test/pageObjects/admin/classes.js
test/pageObjects/admin/members.js
test/specs/admin-e2e.js
test/specs/member-e2e.js
test/specs/superadmin-e2e.js
test/specs/trainer-e2e.js

Added automation test for Crud of classes from admin flow.
Fix the members issue in the test.
Fix the routes for LogIn file.

MR-198/MR-203: Automation classes crud, fixes for members test and logIn routes

---

src/Components/Admin/Admins/Form/index.jsx
src/Components/Admin/Admins/Profile/index.js

added new test id about form on profile of  admin

MR-204: automation - add test id for profile of form

---

src/Components/Admin/Admins/index.js
src/Components/SuperAdmins/index.jsx

Fixed test id for super admins

MR-208:Fixed test id for super admins

---

test/pageObjects/navbar/adminNavbar.js
test/pageObjects/navbar/memberNavbar.js
test/pageObjects/sharedComponents/login.js
test/pageObjects/sharedComponents/modalAlert.js
test/pageObjects/sharedComponents/modalConfirm.js
test/specs/admin-e2e.js
test/specs/member-e2e.js

In this PR I fix two e2e flows. In the future, more tests may be added.

MR-191: corrections automated tests

---

src/Components/Member/Schedule/index.jsx
src/Components/Shared/SharedSchedule/index.jsx
src/Components/SuperAdmins/Admins/Form/index.jsx
src/Components/SuperAdmins/Admins/index.js

In this PR I added test id to the shared schedule and in the member schedule. Also, I added test-id to the SuperAdmin entity.

MR-210: new test id in schedule and in SA entity

---

test/pageObjects/superAdmin/adminCRUD.js
test/specs/superadmin-e2e.js

Waiting for the merge of #106  to see if the edit are functional.

MR-209: Automation SA - Corrected some selectors and added the delete function

---

src/redux/classes/thunks.js

In this PR changed the response message when deleting a class in the admin flow to the recommended one.

BaSP-MR-216: New response msg for delete class in Admin.

---

src/Components/Admin/Admins/EditPassword/password.module.css
src/Components/Member/ProfileEditPass/index.jsx
test/pageObjects/member/changePassword.js
test/pageObjects/member/profileForm.js
test/pageObjects/sharedComponents/signIn.js
test/specs/member-e2e.js

in this PR I finished all the automation for a member. Schedule flow is not automated due to some conflicts with the schedule.

MR-221: finished member automation and fix edit pass style

---

src/Components/Admin/Activities/Form/index.jsx
src/Components/Admin/Activities/index.js
src/Components/Admin/Admins/index.js
src/Components/Admin/Classes/Form/index.jsx
src/Components/Admin/Classes/index.jsx
src/Components/Admin/Members/index.js
src/Components/Admin/Subscriptions/index.jsx
src/Components/Admin/Trainers/Form/index.jsx
src/Components/Admin/Trainers/index.jsx
src/Components/Member/Activity/index.js
src/Components/Shared/LoadingSpinner/index.jsx
src/Components/Shared/LoadingSpinner/loading-spinner.module.css
src/Components/SuperAdmins/Admins/index.js
src/Components/SuperAdmins/index.jsx
src/Components/Trainer/Profile/index.jsx

In this PR a loadingSpinner was created and applied to pages that had some isLoading implemented.

BaSP-MR-223: Loading spinner

---

src/Components/Admin/Admins/EditPassword/password.module.css
src/Components/Admin/Classes/Form/index.jsx
src/Components/Member/Membership/membership.module.css
src/Components/Shared/SharedSchedule/index.jsx
test/pageObjects/admin/trainersPage.js
test/specs/admin-e2e.js

MR-224: fix admin automation
